# Generated by Django 5.0.2 on 2024-05-13 16:23

import django.core.validators
import django.db.models.deletion
import kennel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], default='M', max_length=1)),
                ('couleur', models.CharField(choices=[('N', 'Noir'), ('NB', 'Noir et Blanc'), ('TC', 'Tricolore'), ('DB', 'Doré et Blanc')], default='TC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Chien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('surnom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], default='M', max_length=1)),
                ('couleur', models.CharField(choices=[('N', 'Noir'), ('NB', 'Noir et Blanc'), ('TC', 'Tricolore'), ('DB', 'Doré et Blanc')], default='TC', max_length=2)),
                ('dob', models.DateField()),
                ('puce', models.CharField(max_length=18, validators=[kennel.models.Chien.validate_puce])),
                ('affixe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kennel.affixe')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('cp', models.CharField(max_length=5, validators=[kennel.models.Client.validate_cp])),
                ('ville', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=14, validators=[kennel.models.Client.validate_tel])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('dobc', models.DateField()),
                ('chiot_choisi', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kennel.chiot')),
            ],
        ),
        migrations.CreateModel(
            name='Portee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('chiot', models.ManyToManyField(to='kennel.chiot')),
                ('mere', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='portees_mere', to='kennel.chien')),
                ('pere', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='portees_pere', to='kennel.chien')),
            ],
        ),
    ]
