# Generated by Django 5.0.2 on 2024-05-02 14:11

import django.db.models.deletion
import kennel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('surnom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], default='M', max_length=1)),
                ('dob', models.DateField()),
                ('puce', models.CharField(max_length=18, validators=[kennel.models.Kennel.validate_puce])),
                ('affixe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kennel.affixe')),
            ],
        ),
    ]
