# Generated by Django 5.0.2 on 2024-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='couleur',
            field=models.CharField(choices=[('N', 'Noir'), ('NB', 'Noir et Blanc'), ('TC', 'Tricolore'), ('DB', 'Doré et Blanc')], default='TC', max_length=2),
        ),
    ]
