# Generated by Django 5.0.2 on 2024-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kilometrage', models.IntegerField()),
                ('prix_au_litre', models.DecimalField(decimal_places=3, max_digits=4)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
