# Generated by Django 5.0.2 on 2024-04-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consogo', '0002_alter_conso_kilometrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conso',
            name='prix_au_litre',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
