# Generated by Django 5.0.2 on 2024-05-13 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('CB', 'Carte Bleue'), ('VRT', 'Virement'), ('ESP', 'Espèces')], default='CB', max_length=3)),
                ('pointage', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=3)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compta.categorie')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kennel.chien')),
            ],
        ),
    ]
