# Generated by Django 5.0.2 on 2024-06-01 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kennel.chien'),
        ),
        migrations.CreateModel(
            name='direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_credit', to='compta.operation')),
                ('debit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_debit', to='compta.operation')),
            ],
        ),
    ]
